import type { Food } from '../types';

const CREATED = '2026-01-01T00:00:00.000Z';

const SEED: Food[] = [
  {
    id: 'seed-yogurt',
    name: 'Greek yogurt, plain',
    servingSize: '170 g',
    calories: 100,
    protein: 17,
    carbs: 6,
    fat: 0.7,
    fiber: 0,
    sodium: 65,
    favorite: false,
    createdAt: CREATED,
    source: 'seed',
  },
  {
    id: 'seed-oats',
    name: 'Rolled oats, dry',
    servingSize: '40 g',
    calories: 150,
    protein: 5,
    carbs: 27,
    fat: 3,
    fiber: 4,
    sodium: 0,
    favorite: false,
    createdAt: CREATED,
    source: 'seed',
  },
  {
    id: 'seed-banana',
    name: 'Banana',
    servingSize: '1 medium (118 g)',
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.4,
    fiber: 3,
    favorite: false,
    createdAt: CREATED,
    source: 'seed',
  },
  {
    id: 'seed-eggs',
    name: 'Eggs',
    servingSize: '2 large',
    calories: 144,
    protein: 12.6,
    carbs: 0.7,
    fat: 9.5,
    sodium: 124,
    favorite: false,
    createdAt: CREATED,
    source: 'seed',
  },
  {
    id: 'seed-chicken',
    name: 'Chicken breast, cooked',
    servingSize: '100 g',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    sodium: 74,
    favorite: false,
    createdAt: CREATED,
    source: 'seed',
  },
  {
    id: 'seed-rice',
    name: 'Brown rice, cooked',
    servingSize: '1 cup (195 g)',
    calories: 216,
    protein: 5,
    carbs: 45,
    fat: 1.8,
    fiber: 3.5,
    sodium: 10,
    favorite: false,
    createdAt: CREATED,
    source: 'seed',
  },
  {
    id: 'seed-salmon',
    name: 'Salmon, cooked',
    servingSize: '100 g',
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    sodium: 61,
    favorite: false,
    createdAt: CREATED,
    source: 'seed',
  },
  {
    id: 'seed-broccoli',
    name: 'Broccoli, cooked',
    servingSize: '1 cup (156 g)',
    calories: 55,
    protein: 3.7,
    carbs: 11,
    fat: 0.6,
    fiber: 5,
    sodium: 64,
    favorite: false,
    createdAt: CREATED,
    source: 'seed',
  },
  {
    id: 'seed-olive-oil',
    name: 'Olive oil',
    servingSize: '1 tbsp (14 g)',
    calories: 119,
    protein: 0,
    carbs: 0,
    fat: 13.5,
    favorite: false,
    createdAt: CREATED,
    source: 'seed',
  },
  {
    id: 'seed-bread',
    name: 'Whole-wheat bread',
    servingSize: '1 slice (43 g)',
    calories: 81,
    protein: 4,
    carbs: 15,
    fat: 1.1,
    fiber: 2,
    sodium: 146,
    favorite: false,
    createdAt: CREATED,
    source: 'seed',
  },
  {
    id: 'seed-almonds',
    name: 'Almonds',
    servingSize: '28 g',
    calories: 164,
    protein: 6,
    carbs: 6,
    fat: 14,
    fiber: 3.5,
    sodium: 0,
    favorite: false,
    createdAt: CREATED,
    source: 'seed',
  },
  {
    id: 'seed-sweet-potato',
    name: 'Sweet potato, baked',
    servingSize: '1 medium (114 g)',
    calories: 103,
    protein: 2,
    carbs: 24,
    fat: 0.2,
    fiber: 3.8,
    sodium: 41,
    favorite: false,
    createdAt: CREATED,
    source: 'seed',
  },
];

export function createSeedFoods(): Food[] {
  return SEED.map((food) => ({ ...food }));
}
